# Corpus Extraction Configuration - Test Mode (100 documents)
# This config is used for testing parallel extraction with a small sample
# Usage: envsubst < cfg/extraction/corpus_extraction_test.yml | python -m stindex.exe.extract_corpus --config -

input:
  corpus_path: "data/original/medcorp/train_textbooks_only.jsonl"

  # Offset and limit set by environment variables (defaults for testing)
  offset: ${WORKER_OFFSET:-0}
  limit: ${WORKER_LIMIT:-100}  # Default to 100 documents for testing

extraction:
  dimension_config: "data/schema_discovery_mirage_textbook/final_schema"
  batch_size: 100
  sample_limit: null

llm:
  llm_provider: "hf"
  model_name: null
  base_url: "http://localhost:8001"

output:
  output_dir: ${WORKER_OUTPUT_DIR:-"data/extraction_results_test"}

indexing:
  corpus_name: "medcorp_textbooks"
  worker_id: ${WORKER_ID:-1}
  num_gpus: ${NUM_GPUS:-4}

# Speed optimizations enabled
spatial:
  enable_osm_context: false

reflection:
  enabled: false
